### PR TITLE
s3: Retry on url.Error too

### PR DESCRIPTION
**Pull request by abustany**
Those errors happen for example when the server closes the response
before sending the response.

One additional question is whether we want to filter on the method before retrying, for example based on the HTTP method.

### CODE REVIEW

**Comment by alimoeeny** [comment]
Thanks @abustany , I have a question. What kind of `errors` fall in to this case? do we really want to retry them?

**Comment by abustany** [comment]
So after reading the source code, it appears that:

- The `url` package can return that error when parsing the URL, in that case `err.Op` will be set to `parse`
- The `http` package can return that error when the request fails on the connection level, in that case `err.Op` will be set to the method name with the first letter in uppercase, and the rest in lowercase (eg. "Put" for PUT etc.).

I guess it makes little sense to retry on URL parse errors (but retrying there is also harmless), for HTTP methods it's a bit hard to decide what makes sense and what doesn't when retrying... Libraries like Apache's http client in Java make that configurable, but I'm not sure in makes much sense here? Apart from POST, all operations in S3 should be idempotent I think.

So as a "conclusion": it would maybe make sense to restrict the retry to the cases where `err.Op` is `Get`, `Put` or `Delete`. If it works for you, I'll amend the patch.

**Comment by alimoeeny** [comment]
Thanks @abustany 
So, did I understood correctly that:
- when the `err.Op` is `parse` there is no need to retry (if that ever happens at this stage?)
- otherwise you are proposing to exclude `POST` and `HEAD` (and others things?) and just retry for `GET`, `PUT`, and `DELETE`   
The reasoning being these three are (or are supposed to be) idempotent calls. 
This all makes sense to me. Except that I was assuming when we can an error at this stage even nothing has happened on the amazon side so we should be able to repeat even 'POST' calls.
and I imagine `HEAD` calls are also safe, right?

**Comment by abustany** [comment]
> when the err.Op is parse there is no need to retry (if that ever happens at this stage?)

Yes, that would be an error doing url parsing, which is not going to go away (if the URL is invalid, it's invalid, period)

> The reasoning being these three are (or are supposed to be) idempotent calls

Correct

> Except that I was assuming when we can an error at this stage even nothing has happened on the amazon side so we should be able to repeat even 'POST' calls

Well we're not sure of that. I used to the following code to reproduce the error locally

```
func requestHandler(w http.ResponseWriter, r *http.Request) {
    rwc, _, _ := w.(http.Hijacker).Hijack()
    rwc.Close()
}
```

as you can see, the request might have already been processed, it's just that the connection is closed before the response headers are received or parsed.

> and I imagine HEAD calls are also safe, right?

Yes, you're right, I had forgotten this one in my list, thanks for pointing it out.

**Comment by alimoeeny** [comment]
Fantastic, thank you for the explanation. Please go ahead when you've got a chance.

**Comment by abustany** [comment]
The latest commit (I amended it) should address your comments, feel free to merge if it's good for you ☺

**Comment by alimoeeny** [comment]
Thanks

**Pull request merged**
